# ...

# zoxide init
eval "$(zoxide init bash --cmd cd)"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

. "$HOME/.cargo/env"

export EDITOR="hx"
export HELIX_RUNTIME=/home/naveen/Documents/Naveen/helix/runtime

disk_usage_ok() {
    local min_gb=${1:-5}
    # Use -k for KB output (most portable), then convert to GB
    local available_kb=$(df -k / | awk 'NR==2 {print $4}')
    local available_gb=$((available_kb / 1024 / 1024))
    [ "$available_gb" -ge "$min_gb" ]
}

# Commands generated by llms
# Conditional commands based on disk usage
if disk_usage_ok 2; then
    # Normal operations - less than 2 GB free
    # Set up fzf key bindings and fuzzy completion
    [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    eval "$(fzf --bash)"

    # >>> mamba initialize >>>
    # !! Contents within this block are managed by 'mamba shell init' !!
    export MAMBA_EXE='/home/naveen/miniforge3/bin/mamba';
    export MAMBA_ROOT_PREFIX='/home/naveen/miniforge3';
    __mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__mamba_setup"
    else
        alias mamba="$MAMBA_EXE"  # Fallback on help from mamba activate
    fi
    unset __mamba_setup
    mamba activate base
    export PATH="/home/naveen/.pixi/bin:$PATH"

    . ~/.just.bash

    function set_win_title(){
        echo -ne "\033]0;ghostty $(basename "$PWD") \007"
    }

    eval "$(starship init bash)"
    starship_precmd_user_func="set_win_title"

    . "/home/naveen/.deno/env"

    # xmodmap -e 'keycode 0x6c = Caps_Lock'
    # xmodmap -e "remove lock = Caps_Lock"
    # xmodmap -e 'keycode 0x42 = Tab'
    export PATH=~/opensim-core/bin:$PATH
    export PATH=$HOME/.atuin/bin:$PATH

    source ~/.local/share/blesh/ble.sh
    bleopt complete_ambiguous=

    # [[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh
    eval "$(atuin init bash)"
    eval "$(zoxide init bash --cmd cd)"
    eval "$(pixi completion --shell bash)"
    source ~/.dufs_completions.bash
else
    # Minimal setup - disk usage 75% or higher
    echo "Not enough storage"
   
fi
# In .bash_aliases
alias clip="xclip -sel clip"
alias zotero="/home/naveen/Downloads/Zotero_linux-x86_64/zotero"
alias ebash="hx ~/.bashrc ~/.bash_aliases"
alias sbash="source ~/.bashrc"
alias pg="ping google.com"
alias vm="virt-manager"
# alias open="nautilus"
alias sudo='sudo '
alias apt='\nala'
alias apt0='\apt'
alias snap='SNAPD_USE_IPV4=1 snap' #apparently ipv6 does not work well on this computer?
cheatsh() {
    curl cheat.sh/"$1"
}
alias netaccess="/home/naveen/Documents/Naveen/netaccess/target/release/netaccess"
alias only="flatpak run org.onlyoffice.desktopeditors"
alias bambu="flatpak run com.bambulab.BambuStudio"
alias ghkey="cat /home/naveen/Documents/Naveen/gh_key | clip"
alias matlab="/usr/local/MATLAB/R2024b/bin/matlab"
alias act="source ./.venv/bin/activate"
mce() {
    if [ $# -eq 0 ]; then
        echo "Usage: mce <environment_name> <python_version>"
        echo "Create a new mamba environment with specified Python version"
        echo ""
        echo "Arguments:"
        echo "  environment_name  Name for the new conda environment"
        echo "  python_version    Python version (e.g., 3.9, 3.10, 3.11)"
        echo ""
        echo "Example:"
        echo "  mce myenv 3.10"
        return 1
    fi
    mamba create -n "$1$2" python=$2
}
alias gdlauncher="~/Downloads/GDL*.AppImage --no-sandbox"
alias zen="flatpak run app.zen_browser.zen"
alias vsc="code ."
# alias size="du -hs * | sort -h" # Use dust instead
alias tectonic="/home/naveen/Downloads/tectonic/GameLinux.x86_64"
alias ls='\eza'
alias ls0='\ls --color=auto'
alias mgba='/home/naveen/Downloads/mGBA-build-latest-appimage-x64.appimage'
# blend(){
#     '/home/naveen/Downloads/blender443/blender-4.4.3-linux-x64/blender-launcher' '$@'
# }
alias blend='/home/naveen/Downloads/blender443/blender-4.4.3-linux-x64/blender-launcher'
alias update_discord='sudo apt install ~/Downloads/discord-*.deb -y; rm ~/Downloads/discord-*.deb'
serve_files(){
        # Check if pattern argument is provided
    if [ $# -eq 0 ]; then
        echo "Usage: serve_files <file_pattern>"
        echo "Example: serve_files '*'"
        return 1
    fi

    PATTERN="$1"
    TEMP_DIR="$HOME/server_folder"

    # Create temporary folder if it doesn't exist
    if [ ! -d "$TEMP_DIR" ]; then
        echo "Creating temporary directory: $TEMP_DIR"
        mkdir -p "$TEMP_DIR"
    else
        echo "Temporary directory already exists: $TEMP_DIR"
    fi

    # Delete all files inside the temporary folder
    echo "Cleaning temporary directory..."
    rm -rf "$TEMP_DIR"/*

    echo "Copying files matching pattern: $PATTERN (case-insensitive)"
    echo "Searching in: ~/Zotero/storage/"
    
    # Use find with case-insensitive matching and copy in one go
    files_copied=$(find ~/Zotero/storage -type f -iname "*${PATTERN}*.pdf" -exec ln -s {} "$TEMP_DIR/" \; -print 2>/dev/null)
    
    if [ -n "$files_copied" ]; then
        echo "Files copied!"
        cd "$TEMP_DIR"
        echo "Starting dufs server from $TEMP_DIR..."
        dufs --allow-symlink
    else
        echo "No files matching pattern '$PATTERN' found!"
    fi
}
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}
